barcus/bareos

client/Dockerfile
I've clean the client Dockerfile (client/Dockerfile). 
If you like it, I can do the others.
=> Clean Dockerfile

director-mysql/16.2/docker-entrypoint.sh, director-mysql/17.2/docker-entrypoint.sh, director-pgsql/16.2/docker-entrypoint.sh, director-pgsql/17.2/docker-entrypoint.sh
The bareos-webui repository [has moved](https://github.com/bareos/bareos-webui) to the main bareos repository.
=> Update fetched config files URLs

README.md, client/18.2/Dockerfile, client/18.2/docker-entrypoint.sh, director-mysql/18.2/Dockerfile, director-mysql/18.2/docker-entrypoint.sh, docker-compose.yml, storage/18.2/Dockerfile, storage/18.2/docker-entrypoint.sh, webui/18.2/Dockerfile, webui/18.2/docker-entrypoint.sh
upgrade ubuntu image with latest BareOS 18.2
=> upgrade ubuntu image 

director-pgsql/16.2/docker-entrypoint.sh, director-pgsql/17.2/docker-entrypoint.sh, director-pgsql/18.2/docker-entrypoint.sh
=> fix perm when bareos lib dir exist

README.md, client/16.2/Dockerfile, client/17.2/Dockerfile, client/18.2/Dockerfile, director-mysql/16.2/Dockerfile, director-mysql/17.2/Dockerfile, director-mysql/17.2/docker-entrypoint.sh, director-mysql/18.2/Dockerfile, director-mysql/18.2/docker-entrypoint.sh, director-pgsql/16.2/Dockerfile, director-pgsql/17.2/Dockerfile, director-pgsql/18.2/Dockerfile, docker-compose-pgsql.yml, docker-compose.yml, storage/16.2/Dockerfile, storage/17.2/Dockerfile, storage/18.2/Dockerfile, webui/16.2/Dockerfile, webui/17.2/Dockerfile, webui/18.2/Dockerfile
Your documentation should use the correct name of the project "Bareos" and not "BareOS".
=> use correct spelling of Bareos

README.md, client/18.2-ubuntu/Dockerfile, client/19.2-ubuntu/Dockerfile, director-mysql/18.2-ubuntu/Dockerfile, director-mysql/19.2-ubuntu/Dockerfile, director-pgsql/18.2-ubuntu/Dockerfile, director-pgsql/19.2-ubuntu/Dockerfile, storage/18.2-ubuntu/Dockerfile, storage/19.2-ubuntu/Dockerfile, webui/18.2-ubuntu/Dockerfile, webui/19.2-ubuntu/Dockerfile
=> Baseimg ubuntu bionic

docker-compose-mysql.yml
barcus/bareos-director:19-ubuntu-mysql is your correct tag
=> fix wrong image name

README.md, client/19-alpine/Dockerfile, client/19-alpine/docker-entrypoint.sh, director-mysql/18-alpine/Dockerfile, director-mysql/19-alpine/Dockerfile, director-mysql/19-alpine/docker-entrypoint.sh, docker-compose-alpine-v1.yml, docker-compose-alpine-v2.yml, storage/18-alpine/Dockerfile, storage/19-alpine/Dockerfile, storage/19-alpine/docker-entrypoint.sh, webui/19-alpine/Dockerfile, webui/19-alpine/docker-entrypoint.sh
- add Bareos 19.2 for Alpine (edge)
- update Alpine 3.10 to 3.12 for Bareos 18.2
- update readme tags
=> Bareos 19.2 for Alpine

client/16-ubuntu/docker-entrypoint.sh, client/17-alpine/docker-entrypoint.sh, client/17-ubuntu/docker-entrypoint.sh, client/18-alpine/docker-entrypoint.sh, client/18-ubuntu/docker-entrypoint.sh, client/19-alpine/docker-entrypoint.sh, client/19-ubuntu/docker-entrypoint.sh
if FORCE_ROOT variable doesn't exist
=> fix entrypoint bareos client

client/20-alpine/Dockerfile, client/20-alpine/docker-entrypoint.sh, director-mysql/19-alpine/Dockerfile, director-mysql/20-alpine/Dockerfile, director-mysql/20-alpine/docker-entrypoint.sh, director-mysql/20-alpine/webhook-notify, director-pgsql/20-alpine/Dockerfile, director-pgsql/20-alpine/docker-entrypoint.sh, director-pgsql/20-alpine/webhook-notify, storage/19-alpine/Dockerfile, storage/20-alpine/Dockerfile, storage/20-alpine/docker-entrypoint.sh, webui/20-alpine/Dockerfile, webui/20-alpine/docker-entrypoint.sh
Note: At this moment, bareos-webui 20 installation is not working on alpine edge #92
=> Freeze alpine for Bareos v19 and add v20

.env.dist, .env.mysql.dist, .github/workflows/run-compose.yml, .gitignore, README.md, docker-compose-alpine-v1.yml, docker-compose-alpine-v2.yml, docker-compose-ubuntu-mysql.yml, docker-compose-ubuntu-pgsql.yml
Hello,
Thanks you for your great work!
May I suggest to use somes dotEnv file to simplify the configuration of this Docker Compose files?
Thank you in advance.
Regards,
=> Add DotEnv files

storage/20-ubuntu/Dockerfile
available only for Bareos v20 with Ubuntu image
=> add bareos-storage-droplet

.env.dist, README.md, director-pgsql/16-ubuntu/docker-entrypoint.sh, director-pgsql/17-ubuntu/docker-entrypoint.sh, director-pgsql/18-ubuntu/docker-entrypoint.sh, director-pgsql/19-alpine/docker-entrypoint.sh, director-pgsql/19-ubuntu/docker-entrypoint.sh, director-pgsql/20-alpine/docker-entrypoint.sh, director-pgsql/20-ubuntu/docker-entrypoint.sh, docker-compose-ubuntu-pgsql.yml
Hello,
Some changes to use a custom PostgreSQL username
Thank you in advance.
Regards,
=> Use custom PostgreSQL username

webui/19-alpine/Dockerfile, webui/19-alpine/docker-entrypoint.sh, webui/20-alpine/Dockerfile, webui/20-alpine/docker-entrypoint.sh
- Fix max_body_size to 20m
- Fix /run/nginx folder creation
=> Max body size nginx

client/20-alpine/Dockerfile, client/20-alpine/docker-entrypoint.sh, client/21-ubuntu/Dockerfile, client/21-ubuntu/docker-entrypoint.sh
* change bareos-fd user/group (vars:  BAREOS_DAEMON_USER / BAREOS_DAEMON_GROUP)
* change bareos-fd user/group ID (vars: PUID / PGID)
* force /etc/bareos to BAREOS_DAEMON_USER:BAREOS_DAEMON_GROUP (default: bareos)
* use gosu/su-exec to exec CMD
=> improve bareos-fd user settings

README.md, director-pgsql/18-ubuntu/docker-entrypoint.sh, director-pgsql/19-alpine/docker-entrypoint.sh, director-pgsql/19-ubuntu/docker-entrypoint.sh, director-pgsql/20-alpine/docker-entrypoint.sh, director-pgsql/20-ubuntu/docker-entrypoint.sh, director-pgsql/21-ubuntu/docker-entrypoint.sh, docker-compose-alpine-pgsql.yml, docker-compose-ubuntu-mysql.yml
* sync director entrypoint with v21
* update docker-compose files
* update readme about db upgrade
=> update pgsql stuff

client/20-alpine/Dockerfile, director-mysql/20-alpine/Dockerfile, director-pgsql/20-alpine/Dockerfile, storage/20-alpine/Dockerfile, webui/20-alpine/Dockerfile
Freeze alpine version 3.15 for Bareos 20
=> freeze alpine version bareos 20

.github/actions/prepare-bareos-app/entrypoint.sh, client/21-alpine/Dockerfile, client/21-alpine/docker-entrypoint.sh, director-pgsql/21-alpine/Dockerfile, director-pgsql/21-alpine/docker-entrypoint.sh, director-pgsql/21-alpine/webhook-notify, storage/21-alpine/Dockerfile, storage/21-alpine/docker-entrypoint.sh, webui/21-alpine/Dockerfile, webui/21-alpine/docker-entrypoint.sh
add dockerfile for bareos 21 alpine
=> Bareos21 alpine

bareos-db-migration/README.md, bareos-db-migration/docker-compose.yml
* add dedicated readme
* move and update docker-compose file
=> improve bareos db migration

docker-compose-alpine-mysql-v2.yml, docker-compose-alpine-mysql.yml, docker-compose-alpine-pgsql.yml, docker-compose-ubuntu-mysql.yml, docker-compose-ubuntu-pgsql.yml
switch from namshi/smtp to devture/exim-relay which is up to date and also available for arm
=> use devture smtp container

storage/20-alpine/docker-entrypoint.sh, storage/20-ubuntu/docker-entrypoint.sh, storage/21-alpine/docker-entrypoint.sh, storage/21-ubuntu/docker-entrypoint.sh
avoid warning ouput when fixing permissions
=> fix warning baeros-sd
